routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::middleware(['auth'])->group(function () {
    Route::resource('contacts', 'ContactController');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('items', 'ItemController');

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Contact extends Model
{
    protected $fillable = ['first_name', 'last_name', 'email', 'phone', 'address','custom_fields'];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function customFields(){
        return $this->hasMany(CustomField::class);
    }

    public function setCustomFieldsAttribute($custom_fields){


        if($custom_fields){

            $custom_fields = array_filter($custom_fields['custom_fields'],function($data){ return isset($data['name'])?true:false;});

            $this->customFields()->delete();
            $this->customFields()->createMany($custom_fields);
        }
    }

}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Contact;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\View;

class ContactController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $user = Auth::user();
        if (View::exists('contacts.index')) {
            return view('contacts.index', compact('user'));
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = Auth::user();
        $contact = new Contact;
        if (View::exists('contacts.create')) {
            return view('contacts.create', compact('user', 'contact'));
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        if (!$this->validate($request, [
            'first_name' => 'required|max:255',
            'last_name' => 'max:255',
            'address' => 'max:255',
            'phone' => 'max:255',
            'email' => 'max:255|email',
            'custom_fields' => ''
        ])
        ) {
            return Redirect::route('contacts.create')
                ->withInput($request->all());
        } else {
            $input = $request->only([
                'first_name',
                'last_name',
                'phone',
                'email',
                'address',
            ]);
            $contact = Auth::user()->contacts()->create($input);
            return Redirect::route('contacts.show',['id'=>$contact->id]);
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = Auth::user();
        $contact = Contact::where(['id'=>$id, 'user_id'=>$user->id])->firstOrFail();
        if (View::exists('contacts.show')) {
            return view('contacts.show', compact('user', 'contact'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = Auth::user();
        $contact = Contact::with('customFields')->where(['id'=>$id, 'user_id'=>$user->id])->firstOrFail();

        if (View::exists('contacts.edit')) {
            return view('contacts.edit', compact('user', 'contact'));
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if (!$this->validate($request, [
            'first_name' => 'required|max:255',
            'last_name' => 'required|max:255',
            'address' => 'required|max:255',
            'phone' => 'required|max:255',
            'email' => 'required|max:255|email',
            'custom_fields' => ''
        ])
        ) {
            return Redirect::route('contacts.create')
                ->withInput($request->all());
        } else {



            $input = $request->only('first_name', 'last_name', 'email', 'phone', 'address');

            $custom_fields = $request->only('custom_fields');

            $user = Auth::user();

            $contact = Contact::where(['id'=>$id, 'user_id'=>$user->id])->firstOrFail();

            $contact->custom_fields = $custom_fields;

            $contact->update($input);

            return Redirect::route('contacts.show',['id'=>$contact->id]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();

        $contact = Contact::where(['id'=>$id, 'user_id'=>$user->id])->firstOrFail();
        $contact->customFields()->delete();
        $contact->delete();
            return Redirect::route('contacts.index');

    }
}

resources/views/contacts/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Create Contact</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @include('contacts.form')

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contacts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit Contact</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @include('contacts.form')

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contacts/form.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if($contact)
{!!  Form::open(['url' => URL::route('contacts.update',['id'=>$contact->id])]) !!}
@else
{!!  Form::open(['url' => URL::route('contacts.create')]) !!}
@endif
{{csrf_field()}}
{{method_field('put')}}

<div class="col-xs-12 col-md-6">
    <div class="form-group">
        {{ Form::label('first_name', 'First name') }}
        {{ Form::text('first_name', old('first_name',$contact->first_name), ['class'=>'form-control']) }}
    </div>
</div>

<div class="col-xs-12 col-md-6">
    <div class="form-group">
        {{ Form::label('last_name', 'Last name') }}
        {{ Form::text('last_name', old('last_name',$contact->last_name), ['class'=>'form-control']) }}
    </div>
</div>

<div class="col-xs-12 col-md-6">
    <div class="form-group">
        {{ Form::label('address', 'Address') }}
        {{ Form::text('address', old('address',$contact->address), ['class'=>'form-control']) }}
    </div>
</div>


<div class="col-xs-12 col-md-6">
    <div class="form-group">
        {{ Form::label('phone', 'Phone') }}
        {{ Form::text('phone', old('phone',$contact->phone), ['class'=>'form-control']) }}
    </div>
</div>

<div class="col-xs-12">
    <div class="form-group">
        {{ Form::label('email', 'Email') }}
        {{ Form::text('email', old('email',$contact->email), ['class'=>'form-control']) }}
    </div>
</div>
<div id="extra_fields">
    @if($contact->customFields()->count())

        @foreach($contact->customFields as  $custom_field)
            <div class="col-xs-6">
                <div class="form-group">
                    {{ Form::label('custom_fields['.$loop->index.'][name]', 'New Field Title ') }}
                    {{ Form::text('custom_fields['.$loop->index.'][name]', $custom_field->name, ['class'=>'form-control']) }}
                </div>
            </div>
            <div class="col-xs-6">
                <div class="form-group">
                    {{ Form::label('custom_fields['.$loop->index.'][value]', 'New Field Value ') }}
                    {{ Form::text('custom_fields['.$loop->index.'][value]', $custom_field->value, ['class'=>'form-control']) }}
                </div>
            </div>
            <?php $line = $loop->index?>

        @endforeach
    @else
        <?php $line = 0?>
    @endif
    <div class="empty_ell"></div>
</div>
<div class="col-xs-12 ">
    <div class="form-group">
        <div class="form-group">
            <a class=" btn btn-default form-control" id="addLine" data-line="{{$line}}"> Add new field</a>
        </div>
    </div>

</div>
    <div class="col-xs-12 ">
        <div class="form-group">
            {!! Form::submit('Submit', ['class'=>'form-control']) !!}
        </div>
    </div>
{!! Form::close() !!}

resources/views/contacts/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Contacts</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                            <div class="row">
                                <div class="col-xs-12">
                                    <a class="btn btn-success"
                                       href="{{route('contacts.create')}}">
                                        <i class="glyphicon glyphicon-plus"></i> Add Contact
                                    </a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12">
                                    <table class="table table-hover">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Controls</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($user->contacts as $contact)
                                            <tr>
                                                <td>
                                                    {{$contact->first_name}} {{$contact->last_name}}
                                                </td>
                                                <td>
                                                    {{$contact->email}}
                                                </td>
                                                <td>
                                                    <a href="{{route('contacts.edit',['id'=>$contact->id])}}" class="btn btn-warning">Edit</a>
                                                    {{Form::open(['url'=>route('contacts.destroy',['id'=>$contact->id])])}}
                                                    {{method_field('delete')}}
                                                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure?')">Delete</button>
                                                    {{Form::close()}}

                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contacts/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Contact</div>

                    <div class="panel-body">
                        @if (session('status'))
                            <div class="alert alert-success">
                                {{ session('status') }}
                            </div>
                        @endif

                        @include('contacts.form')

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection